env:
    node: true
parser: "@babel/eslint-parser"
parserOptions:
    requireConfigFile: false
extends: ['airbnb-base', 'prettier']
rules:
  no-plusplus: 0
  func-names: 0
  prettier/prettier: ['error']
plugins:
  - 'prettier'
