env:
    node: true
parser: '@babel/eslint-parser'
extends: 
  - 'airbnb-base'
  - 'prettier'
plugins:
  - 'prettier'
  - 'import'

rules:
  prettier/prettier: ['error', 
    {'singleQuote': true}]
  no-plusplus: 0
  func-names: 0
  import/no-unresolved: 2
  import/no-commonjs: 2
  import/extensions: [2, "ignorePackages"]