env:
    node: true
parser: '@babel/eslint-parser'
parserOptions:
    requireConfigFile: false
extends: ['airbnb-base', 'prettier']
rules:
  prettier/prettier: ['error', 
    {'singleQuote': true}]
  no-plusplus: 0
  func-names: 0

plugins:
  - 'prettier'
