# syntax=docker/dockerfile:1

FROM node:21-alpine

WORKDIR /app
COPY . .

RUN apk add --no-cache bash
RUN apk add --no-cache git

RUN corepack enable
RUN npm install --global pm2
RUN pm2 install pm2-logrotate
RUN yarn install

CMD ["pm2-runtime",  "start", "pm2.config.cjs"]