FROM keymetrics/pm2:latest-alpine

# Not tested nor used -- copy paste from https://pm2.io/docs/runtime/integration/docker/#set-a-dockerfile essentially

# Bundle APP files
COPY src src/
COPY package.json .
COPY ecosystem.config.js .

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

# Expose the listening port of your app
# EXPOSE 8000

# Show current folder structure in logs
RUN ls -al -R

CMD [ "pm2-runtime", "start", "pm2.config.js" ]
