// @index(['./**/*.ts'], (f, _) => `export { default as ${_.pascalCase(f.name)} } from '${f.path}.js';`)
export { default as Back } from './back.js';
export { default as Bassboost } from './bassboost.js';
export { default as Clear } from './clear.js';
export { default as History } from './history.js';
export { default as Jump } from './jump.js';
export { default as Loop } from './loop.js';
export { default as Np } from './np.js';
export { default as Pause } from './pause.js';
export { default as Play } from './play.js';
export { default as Playnext } from './playnext.js';
export { default as Queue } from './queue.js';
export { default as Remove } from './remove.js';
export { default as Resume } from './resume.js';
export { default as Seek } from './seek.js';
export { default as Shuffle } from './shuffle.js';
export { default as Skip } from './skip.js';
export { default as Stop } from './stop.js';
export { default as Volume } from './volume.js';
