env:
  jest: true
plugins:
  - jest

extends:
  - ../.eslintrc.json
  - plugin:jest/style
  - plugin:jest/recommended

rules:
  jest/no-focused-tests: warn
  jest/prefer-spy-on: warn
  jest/prefer-todo: error
  jest/prefer-expect-assertions:
    [error, { "onlyFunctionsWithAsyncKeyword": true }]
